Update parameter.yaml

diff --git a/.github/workflows/parameter.yaml b/.github/workflows/parameter.yaml
--- a/.github/workflows/parameter.yaml
+++ b/.github/workflows/parameter.yaml
@@ -20,9 +20,16 @@ jobs:
       run:
         working-directory: ./postgress
     steps:
-      # Step 1: Checkout the repository metadata
-      - name: Checkout Repository Metadata
-        uses: actions/checkout@v4
+      - name: make sure workflow_dispatch is from develop and master 
+        id: check_workflow_dispatch
+        run: |
+          ALLOWED_BRANCHES=("develop" "main")
+          INPUT_BRANCH="${{ github.event.inputs.branch }}"
+
+          if [[ -z "$INPUT_BRANCH" ]]; then  # Check if input is empty
+            echo "::error::Branch input is required for workflow_dispatch"
+            exit 1
+          fi
 
     outputs:
       merged: ${{ github.event.pull_request.merged || github.event_name == 'workflow_dispatch' }}
